# ----------
#  Makefile.global.in
# 
#       Autoconf input file for Makefile.global
# 
#       Copyright (c) 2020 Marc Munro
#       Author:  Marc Munro
# 	License: GLP V3
#  
#  ----------
#

# Version information
PACKAGE_NAME=		veil2
VEIL_VERSION=		0.9.1 (beta)
VERSION=		0.9.1 (beta)
MAJOR_VERSION=		0
MINOR_VERSION=		9


XSLTPROC = xsltproc
DOCBOOK_ENTITIES = /usr/share/xml/docbook/schema/dtd/4.5/dbcentx.mod
DOCBOOK_STYLESHEETS = /usr/share/xml/docbook/stylesheet/docbook-xsl

